version: '3'
services: 
    my-node-app:
        image: ahussien/my-app:1.1 
        ports: 
            - 4002:3000
        depends_on:
            - "mongodb"
    mongodb:
        image: mongo
        ports: 
            - 4000:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret 
        volumes: 
            - /Users/jomaa/AHG/workspace/devops:/data/db
    mongo-express:
        image: mongo-express
        depends_on:
            - "mongodb"
        ports: 
            - 4001:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin    
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
            - ME_CONFIG_MONGODB_SERVER=mongodb